"""empty message

Revision ID: 1813a362d0c9
Revises: b6c1bdd2b555
Create Date: 2022-04-12 13:00:45.353559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1813a362d0c9'
down_revision = 'b6c1bdd2b555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.drop_constraint('messages_profile_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'profiles', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'profiles', ['recipient_id'], ['id'])
    op.drop_column('messages', 'profile_id')
    op.add_column('profiles', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'last_message_read_time')
    op.add_column('messages', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_profile_id_fkey', 'messages', 'profiles', ['profile_id'], ['id'])
    op.drop_column('messages', 'sender_id')
    op.drop_column('messages', 'recipient_id')
    # ### end Alembic commands ###
