"""empty message

Revision ID: a3d4a2b9ab51
Revises: 8575334b1f71
Create Date: 2022-04-11 12:54:21.709993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d4a2b9ab51'
down_revision = '8575334b1f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('dob', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('location', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('vibe_check', sa.String(length=200), nullable=True))
    op.add_column('profiles', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('sun_sign', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('moon_sign', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('rising_sign', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('gender_identity', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('orientation', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('smoke', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('drink', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('four_twenty', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('is_sober', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_sober')
    op.drop_column('profiles', 'four_twenty')
    op.drop_column('profiles', 'drink')
    op.drop_column('profiles', 'smoke')
    op.drop_column('profiles', 'orientation')
    op.drop_column('profiles', 'gender_identity')
    op.drop_column('profiles', 'profile_picture')
    op.drop_column('profiles', 'rising_sign')
    op.drop_column('profiles', 'moon_sign')
    op.drop_column('profiles', 'sun_sign')
    op.drop_column('profiles', 'bio')
    op.drop_column('profiles', 'vibe_check')
    op.drop_column('profiles', 'location')
    op.drop_column('profiles', 'dob')
    # ### end Alembic commands ###
