"""empty message

Revision ID: ed71bb02b5b6
Revises: e7dc79abdc21
Create Date: 2022-04-13 12:08:55.703196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed71bb02b5b6'
down_revision = 'e7dc79abdc21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_num', sa.Integer(), nullable=True),
    sa.Column('recipient_num', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['recipient_num'], ['profiles.recipient_num'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['sender_num'], ['profiles.sender_num'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('profiles', sa.Column('sender_num', sa.Integer(), nullable=False))
    op.add_column('profiles', sa.Column('recipient_num', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'profiles', ['sender_num'])
    op.create_unique_constraint(None, 'profiles', ['recipient_num'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'recipient_num')
    op.drop_column('profiles', 'sender_num')
    op.drop_table('associations')
    # ### end Alembic commands ###
